spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect


  flyway:
    baselineOnMigrate: true
    user: sa
    password: password
    url: jdbc:h2:mem:testdb
    table: flyway_schema_history
    enabled: true